# permissions for end users to edit dynamicresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicresource-editor-role
rules:
- apiGroups:
  - dynamic.kube
  resources:
  - dynamicresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamic.kube
  resources:
  - dynamicresources/status
  verbs:
  - get
