# permissions for end users to view dynamicresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicresource-viewer-role
rules:
- apiGroups:
  - dynamic.kube
  resources:
  - dynamicresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dynamic.kube
  resources:
  - dynamicresources/status
  verbs:
  - get
