---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - meta.kube
  resources:
  - metaressources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meta.kube
  resources:
  - metaressources/finalizers
  verbs:
  - update
- apiGroups:
  - meta.kube
  resources:
  - metaressources/status
  verbs:
  - get
  - patch
  - update
