apiVersion: dynamic.kube/v1alpha1
kind: DynamicResource
metadata:
  name: dynamicresource-sample
spec:
  target:
    apiVersion: v1
    kind: Secret
    metadata:
      name: generated-secret
      namespace: default
