apiVersion: dynamic.kube/v1alpha1
kind: DynamicResource
metadata:
  name: metaressource-sample
spec:
  transformations:
    - fieldFrom:
        apiVersion: v1
        kind: Secret
        name: dummy-secret
        fieldSpec: "{{.data.foo}}"  # go-template, root is the source object
      targetField: data.generated

  target:
    apiVersion: v1
    kind: Secret
    metadata:
      name: generated-secret
      namespace: default
