apiVersion: meta.kube/v1alpha1
kind: MetaRessource
metadata:
  name: metaressource-sample
spec:
  target:
    apiVersion: v1
    kind: Secret
    metadata:
      name: generated-secret
      namespace: default
