//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Tilman Eggers.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResource) DeepCopyInto(out *DynamicResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResource.
func (in *DynamicResource) DeepCopy() *DynamicResource {
	if in == nil {
		return nil
	}
	out := new(DynamicResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResourceList) DeepCopyInto(out *DynamicResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResourceList.
func (in *DynamicResourceList) DeepCopy() *DynamicResourceList {
	if in == nil {
		return nil
	}
	out := new(DynamicResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResourceSpec) DeepCopyInto(out *DynamicResourceSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]DynamicResourceTransformation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResourceSpec.
func (in *DynamicResourceSpec) DeepCopy() *DynamicResourceSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResourceStatus) DeepCopyInto(out *DynamicResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResourceStatus.
func (in *DynamicResourceStatus) DeepCopy() *DynamicResourceStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicResourceTransformation) DeepCopyInto(out *DynamicResourceTransformation) {
	*out = *in
	out.FieldFrom = in.FieldFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicResourceTransformation.
func (in *DynamicResourceTransformation) DeepCopy() *DynamicResourceTransformation {
	if in == nil {
		return nil
	}
	out := new(DynamicResourceTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalFieldRef) DeepCopyInto(out *ExternalFieldRef) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalFieldRef.
func (in *ExternalFieldRef) DeepCopy() *ExternalFieldRef {
	if in == nil {
		return nil
	}
	out := new(ExternalFieldRef)
	in.DeepCopyInto(out)
	return out
}
